version: '3.8'

services:
  naming-service:
    image: isaacafrifa/forex-naming-service:0.0.1-SNAPSHOT
    ports:
      - "8761:8761"
    deploy:
      resources:
        limits:
          memory: 700M
    networks:
      - forex-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    deploy:
      resources:
        limits:
          memory: 300M
    networks:
      - forex-network

  zipkin-server:
    image: openzipkin/zipkin
    deploy:
      resources:
        limits:
          memory: 300M
    ports:
      - "9411:9411"
    networks:
      - forex-network
    restart: always #Restart if there is a problem starting up

  exchange-rate-service:
    image: isaacafrifa/forex-exchange-rate-service:0.0.1-SNAPSHOT
    deploy:
      resources:
        limits:
          memory: 700M
    ports:
      - "8000:8000"
    networks:
      - forex-network
    depends_on:
      - naming-service
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-service:8761/eureka
      SPRING.ZIPKIN.BASE-URL: http://zipkin-server:9411

  conversion-service:
    image: isaacafrifa/forex-conversion-service:0.0.1-SNAPSHOT
    deploy:
      resources:
        limits:
          memory: 700M
    ports:
      - "8100:8100"
    networks:
      - forex-network
    depends_on:
      - naming-service
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-service:8761/eureka
      SPRING.ZIPKIN.BASE-URL: http://zipkin-server:9411

  api-gateway:
    image: isaacafrifa/forex-api-gateway:0.0.1-SNAPSHOT
    deploy:
      resources:
        limits:
          memory: 700M
    ports:
      - "8765:8765"
    networks:
      - forex-network
    depends_on:
      - naming-service
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-service:8761/eureka
      SPRING.ZIPKIN.BASE-URL: http://zipkin-server:9411
      
networks:
  forex-network: